#!/bin/bash
set -euo pipefail

source scripts/utils/colors.sh
source scripts/utils/prompt.sh
source scripts/utils/require.sh

require_cmd openssl

# Cloudflare files are optional (you may run install without cloudflare)
CF_TUNNEL_ID=""
CF_TUNNEL_NAME="sensualbyte-tunnel"
if [ -f ".cf_tunnel_id" ]; then
  CF_TUNNEL_ID="$(cat .cf_tunnel_id)"
fi
if [ -f ".cf_tunnel_name" ]; then
  CF_TUNNEL_NAME="$(cat .cf_tunnel_name)"
fi

if [ -f ".env" ]; then
  log_warn ".env already exists."
  if ! confirm "Regenerate .env (overwrite)?"; then
    exit 0
  fi
fi

# ---------- Prompts (defaults are production + docker network) ----------
BASE_DOMAIN="$(prompt "Base domain" "sensualbyte.com")"

# Core
NODE_ENV="$(prompt "NODE_ENV" "production")"

# API
API_PORT="$(prompt "API_PORT" "3001")"
CORS_ORIGINS="$(prompt "CORS_ORIGINS (comma-separated)" "http://localhost:8080")"
TRUST_PROXY="$(prompt "TRUST_PROXY (true/false)" "false")"

# DBs (docker network hostnames)
MONGO_URI="$(prompt "MONGO_URI" "mongodb://sb-mongo:27017")"
MONGO_DB="$(prompt "MONGO_DB" "sensualbyte_authority")"
REDIS_URL="$(prompt "REDIS_URL" "redis://sb-redis:6379")"

# MinIO
MINIO_ROOT_USER="$(prompt "MINIO_ROOT_USER" "minioadmin")"
MINIO_ROOT_PASSWORD="$(prompt "MINIO_ROOT_PASSWORD" "minioadmin")"
MINIO_ENDPOINT="$(prompt "MINIO_ENDPOINT" "sb-minio")"
MINIO_PORT="$(prompt "MINIO_PORT" "9000")"


# Worker + provisioner / docker
DEFAULT_DOCKER_NETWORK="$(prompt "DEFAULT_DOCKER_NETWORK" "sb_net")"

# IMPORTANT: worker inside container writes routes to this path (volume mount)
NGINX_CONTAINER_NAME="$(prompt "NGINX_CONTAINER_NAME" "sb-nginx")"
NGINX_CONF_DIR="$(prompt "NGINX_CONF_DIR (inside worker container)" "/var/sb/nginx/conf.d")"

SSH_HOST="$(prompt "SSH_HOST (shown to users)" "localhost")"

RBAC_ENFORCE="$(prompt "RBAC_ENFORCE (true/false)" "false")"

# Secrets
MASTER_KEY_HEX="$(prompt "MASTER_KEY_HEX (blank = auto-generate)" "")"
if [ -z "$MASTER_KEY_HEX" ]; then
  MASTER_KEY_HEX="$(openssl rand -hex 32)" # 32 bytes => 64 hex chars
fi

# Optional JWT secret (some auth flows may use it)
JWT_SECRET="$(prompt "JWT_SECRET (blank = auto-generate)" "")"
if [ -z "$JWT_SECRET" ]; then
  JWT_SECRET="$(openssl rand -hex 32)"
fi

# Safety
DB_RESET="$(prompt "DB_RESET (true/false)" "false")"

# Cloudflare tunnel token (optional if using token-based run)
CLOUDFLARE_TUNNEL_TOKEN="$(prompt "CLOUDFLARE_TUNNEL_TOKEN (optional)" "")"

# ---------- Write .env ----------
cat > .env <<EOF
# =============================================================================
# Sensualbyte Platform (v1) - Root .env (generated by scripts/install/env.sh)
# =============================================================================

# --- Core ---
NODE_ENV=${NODE_ENV}
PLATFORM_NAME=sensualbyte

# --- API ---
API_HOST=0.0.0.0
API_PORT=${API_PORT}
JWT_SECRET=${JWT_SECRET}
CORS_ORIGINS=${CORS_ORIGINS}
TRUST_PROXY=${TRUST_PROXY}

# --- Mongo ---
MONGO_URI=${MONGO_URI}
MONGO_DB=${MONGO_DB}
MONGO_URL=${MONGO_URI}/${MONGO_DB}

# --- Redis ---
REDIS_URL=${REDIS_URL}

# --- RBAC ---
RBAC_ENFORCE=${RBAC_ENFORCE}

# --- Worker (controllers) ---
WORKER_ID=worker_1
WORKER_POLL_INTERVAL_MS=400
OBSERVED_TTL_SECONDS=360
OUTBOX_LOCK_MS=15000
WORKER_DRIFT_SWEEP_ENABLED=true
WORKER_DRIFT_SWEEP_INTERVAL_MS=5000
WORKER_DRIFT_SWEEP_LIMIT=50

# --- Docker / Provisioner ---
DOCKER_SOCKET=/var/run/docker.sock
DEFAULT_DOCKER_NETWORK=${DEFAULT_DOCKER_NETWORK}

# --- Nginx gateway ---
NGINX_CONTAINER_NAME=${NGINX_CONTAINER_NAME}
NGINX_CONF_DIR=${NGINX_CONF_DIR}

# --- MinIO ---
MINIO_ENDPOINT=${MINIO_ENDPOINT}
MINIO_PORT=${MINIO_PORT}
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_USE_SSL=false

# --- SSH box convenience ---
SSH_HOST=${SSH_HOST}

# --- Secrets encryption (required) ---
MASTER_KEY_HEX=${MASTER_KEY_HEX}

# --- DB setup safety ---
DB_RESET=${DB_RESET}

# --- Cloudflare ---
BASE_DOMAIN=${BASE_DOMAIN}
CF_TUNNEL_ID=${CF_TUNNEL_ID}
CF_TUNNEL_NAME=${CF_TUNNEL_NAME}
CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
EOF

log_ok ".env generated."

# Quick sanity checks
if ! echo "$MASTER_KEY_HEX" | grep -Eq '^[0-9a-fA-F]{64}$'; then
  log_warn "MASTER_KEY_HEX does not look like 64 hex chars. Encryption/decryption will fail."
fi
