# generated by sensualbyte provisioner
# DO NOT EDIT BY HAND

server {
  listen 80;
  server_name __HOSTNAME__;

  # basic hardening (optional)
  server_tokens off;

  location __PATH_PREFIX__ {
    proxy_pass http://__TARGET_IP__:__TARGET_PORT__;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # websocket upgrade support
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # timeouts (safe defaults)
    proxy_connect_timeout 5s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }
}
