#!/bin/bash
set -euo pipefail

echo "🧪 Dev mode (recommended)"
echo ""
echo "Prereqs:"
echo " - Docker running"
echo " - Node.js installed"
echo ""
echo "1) Start API (dev):"
echo "   cd apps/api && npm i && npm run dev"
echo ""
echo "2) Start Dashboard (dev):"
echo "   cd apps/dashboard/frontend && npm i && npm start"
echo ""
echo "3) Infra (optional, for gateway/tunnel):"
echo "   docker compose -f infra/docker-compose.yml up -d nginx cloudflared"
echo ""
echo "Tip:"
echo " - If your API needs docker provisioning, it must access /var/run/docker.sock (compose does this)."
