tunnel: sensualbyte-tunnel
credentials-file: /home/nonroot/.cloudflared/330f4e61-835f-45b1-bbdd-37a18444ff00.json

ingress:
  - hostname: nginx.sensualbyte.com
    service: http://localhost:8080
  - hostname: ecs.sensualbyte.com
    service: http://localhost:8080
  - hostname: "*.ecs.sensualbyte.com"
    service: http://localhost:8080

  - hostname: ssh.sensualbyte.com
    service: tcp://localhost:2222

  - service: http_status:404
